### PR TITLE
created an about page.

### PR DESCRIPTION
**Pull request by aapJoysakoi**
Closes:  https://github.com/Avdhesh-Varshney/chanakya-niti/issues/91

- **Title** :  created an about page
- **Name:**  Joysa Kaushik
- **Role:** SSOC 

### Describe the add-ons or changes you've made 📃
-created an about page which displays image of and info. about Aacharya Chanakya.

### Type of change ☑️

- [x] My code follows the code style of this project
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

image

image

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@aapJoysakoi Looks Great. I'm thinking to keep the css files apart from the project structure. So, create `css` named folder aside `pages` or just inside `src`. Then keep your `About.css`  file iniit.

**Comment by aapJoysakoi** [comment]
hey, I made the requested changes. please have a look at it and let me know if any other modifications are required. I've currently added only about.css file in the separate folder in src.. I think that's what you meant (or to add all the css files in that folder?)

**Review by kushagra-singhh — APPROVED** [review]
looks great !! ✨

**Review by Avdhesh-Varshney — APPROVED** [review]
@aapJoysakoi PR Approved 🎉

**Pull request merged**
