### PR TITLE
[#163] created contribution detail page

### PR DESCRIPTION
**Pull request by Madhavdua**
Closes: 

- **Title** : Created contribution detail page
- **Name:** Madhav Dua
- **Idenitfy yourself:**SSOC Contributor

Created detail page as asked.

### Type of change ☑️

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ x] My changes generate no new warnings.

### Screenshots 📷
Screenshot 2024-06-30 021444

### Note to reviewers 📄
Kindly review it and merge it

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@Madhavdua design the details page and show the details of only merged prs. like, it's title, assigned labels, redirecting button, etc. a proper card arrangement of contributors merged prs.

**Comment by Madhavdua** [comment]
For each merged PR:
1.Title
2.Labels, each with descriptions.
3.Seperate redirect link
4.Creation and closed date

Here's the screenshot: 
Screenshot 2024-07-01 232336

**Review by Avdhesh-Varshney — APPROVED** [review]
@Madhavdua looks interesting. PR Approved 🎉

**Comment by Avdhesh-Varshney** [comment]
@Madhavdua properly link your issue. I've mentioned you so many times.

**Pull request merged**
