### PR TITLE
implement auto paging

### PR DESCRIPTION
**Pull request by skanarul8002**
Closes: #292

- **Title** : Implement Auto-Swapping News Cards with Pagination
- **Name:** Sk Anarul
- **Idenitfy yourself:** GSSOC-EXT, Hacktoberfest 

### Describe the add-ons or changes you've made 📃

- Implemented a feature to auto-swap news cards in the carousel, providing dynamic updates for the latest content.
- Added pagination to allow users to browse through more news items seamlessly.
- Each cycle shows different news cards fetched from the API, ensuring fresh content is always displayed.
- Enhanced user experience with smooth transitions and easy navigation.

### Type of change ☑️
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️
- [x] My code follows the Contributing Guidelines & Code of Conduct of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷
https://github.com/user-attachments/assets/981f1fa4-9061-4566-a5e9-138bfc5dcc4e

### Note to reviewers 📄
Thanks team

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
Maintain the website theme color.
Card is not looks good.

**Comment by skanarul8002** [comment]
Ok sure @Avdhesh-Varshney

**Comment by skanarul8002** [comment]
please @Avdhesh-Varshney merge the pr.
see the demo:
Uploading Chanakya.mp4…

**Comment by skanarul8002** [comment]
@Avdhesh-Varshney , by mistakenly i deleted the fork pr😟. I raise a new for the issue #292

**Pull request closed without merging**
