### PR TITLE
Added a eye for pw visibility

### PR DESCRIPTION
**Pull request by pani2004**
Closes: #216 

- **Title** : Added a eye for pw visibility
- **Name:** Debashis Pani
- **Idenitfy yourself:** GSSOC

### Describe the add-ons or changes you've made 📃
I have added a eye button for password toggling
Give a clear description of what have you added or modifications made

### Type of change ☑️

What sort of change have you made:

- [x ] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

- [x ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] I have performed a self-review of my own code.
- [ x] My changes generate no new warnings.

### Screenshots 📷

https://github.com/user-attachments/assets/2c646660-eded-4d22-bd1f-a8261d2884fd

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
image

**Comment by pani2004** [comment]
@Avdhesh-Varshney Made the changes check now

**Comment by Avdhesh-Varshney** [comment]
Can you re-raise the as it has a lots of conflicts?

**Comment by pani2004** [comment]
okk @Avdhesh-Varshney

**Pull request closed without merging**
