### PR TITLE
Added next episode button

### PR DESCRIPTION
**Pull request by Atanu789**
Added a next episode button which plays the next episode

### CODE REVIEW

**Comment by Atanu789** [comment]
i have added a feature "Next Episode" 
kindly review and merge the PR @Avdhesh-Varshney

**Review by Avdhesh-Varshney — COMMENTED** [review]
@Atanu789 this is not looks good for a good ui.

**Comment by Atanu789** [comment]
ok  i will make it suitable for the ui @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@Atanu789 leave it not required.

**Pull request closed without merging**
