### PR TITLE
error 404

### PR DESCRIPTION
**Pull request by taneeshaa15**
Hi @Avdhesh-Varshney  ,
I hope you're doing well. I've addressed the issue #145  and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@taneeshaa15 i think you know this is an react project not a static website. That's why your pr is not deployed and don't change `settings.json` file.

Always create pr on your new branch not on main branch.

**Comment by taneeshaa15** [comment]
@Avdhesh-Varshney I changed the files to react files, please review and tell me what more adjustments are needed.

**Comment by Avdhesh-Varshney** [comment]
image

where is your 404 page?

**Comment by taneeshaa15** [comment]
@Avdhesh-Varshney Will look into this issue and fix it as soon as possible.

**Pull request closed without merging**
