### PR TITLE
Dark/Light mode

### PR DESCRIPTION
**Pull request by sharmi4590**
Closes:  issue #245

- **Title** : Dark/Light mode is not applicable to whole page
- **Name:** Bheemisetty Sharmila
- **Idenitfy yourself:** GSSOC

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
Initially the Dark/Light mode was only applicable on the navbar and footer now I have made it for the Home page as well as the about page.

### Type of change ☑️

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

Screenshot (665)
Screenshot (666)
Screenshot (667)
Screenshot (668)

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
Apply it not only on component upto about, but on overall website.

**Comment by sharmi4590** [comment]
Done .
Screenshot (683)
Screenshot (684)
Screenshot (685)
Screenshot (686)

**Comment by sharmi4590** [comment]
@Avdhesh-Varshney Please check the PR

**Comment by Avdhesh-Varshney** [comment]
Don't delete the carousel or any other part

**Comment by sharmi4590** [comment]
> Don't delete the carousel or any other part

I haven't deleted anything could you please tell me which part i removed specifically?

**Comment by Avdhesh-Varshney** [comment]
> > Don't delete the carousel or any other part
> 
> I haven't deleted anything could you please tell me which part i removed specifically?

image

**Comment by sharmi4590** [comment]
Done , due to merging of other PRs it got deleted nd now it has been cleared. @Avdhesh-Varshney please check once
Screenshot (689)

**Comment by sharmi4590** [comment]
Hey @Avdhesh-Varshney could u please merge it fast as today is the last date that too evening

**Review by Avdhesh-Varshney — APPROVED** [review]

**Pull request merged**
