### PR TITLE
chanakya-error

### PR DESCRIPTION
**Pull request by taneeshaa15**
Screenshot from 2024-07-08 22-42-12

Error Page.

Hi @Avdhesh-Varshney ,
I hope you're doing well. I've addressed the issue #145  and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

### CODE REVIEW

**Comment by taneeshaa15** [comment]
@Avdhesh-Varshney Please review it now.

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
can you show me your working video?

review your own deployed pr
https://chanakya-git-fork-taneeshaa15-main-avdheshvarshneys-projects.vercel.app/abouts

**Comment by taneeshaa15** [comment]
@Avdhesh-Varshney Here is the working video of my error page.

[Screencast from 2024-07-09 15-39-26.webm](https://github.com/Avdhesh-Varshney/chanakya-niti/assets/157527085/9820f9f9-9fdb-4f1f-b6c2-ae856fbf9365)

**Comment by Avdhesh-Varshney** [comment]
404 page should comes up when user goes on an inappropriate route. But you have create a seprate route for error page?

**Comment by taneeshaa15** [comment]
@Avdhesh-Varshney Please review.

**Pull request closed without merging**
