### PR TITLE
Integrate Password Recovery Feature

### PR DESCRIPTION
**Pull request by saras-69**
Closes: 

- **Title** :  Integrate Password Recovery Feature
- **Name:** 
- **Idenitfy yourself:** 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

This PR introduces a password recovery feature that allows users to reset their forgotten passwords through OTP simulation using alerts. The feature adds a responsive interface and smooth user experience. It can later be enhanced with API integration for real OTP verification.

### Checklist: ☑️

- [ x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [ x] My changes generate no new warnings.

### Screenshots 📷

https://github.com/user-attachments/assets/9c10d9d8-5cfb-4da9-a066-7edd7536fd3d

Screenshot 2024-10-22 001505

### Note to reviewers 📄

This feature currently simulates OTP verification via alerts. Future improvements can include backend API integration for actual OTP handling. Your feedback is highly appreciated! 🚀

### CODE REVIEW

**Comment by saras-69** [comment]
Okay

**Comment by Avdhesh-Varshney** [comment]
Link your issue and resolve conflicts.

**Review by Avdhesh-Varshney — COMMENTED** [review]
`/auth/password-recovery` Page not found. Not working as expected

**Comment by saras-69** [comment]
@Avdhesh-Varshney can give me some time, I will fix when I tested it's working fine as you see in video

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney can give me some time, I will fix when I tested it's working fine as you see in video

Ok, re-raise your pr before 5 pm and don't forget to link your issue with pr

**Pull request closed without merging**
