### PR TITLE
feat: share episodes

### PR DESCRIPTION
**Pull request by Sid-80**
Closes: 

- **Title** : Share episodes
- **Name:** Siddharth
- **Idenitfy yourself:** GSSOC

### Describe the add-ons or changes you've made 📃
I implemented the share feature for sharing episodes.

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Screenshots 📷
Share Button :
image

After clicking on share button:
image

### CODE REVIEW

**Comment by Sid-80** [comment]
@Avdhesh-Varshney Please review it!!

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
resolve merge conflicts

**Comment by Sid-80** [comment]
@Avdhesh-Varshney Conflicts resolved!!

**Comment by Avdhesh-Varshney** [comment]
not worked. show me the working the video

**Pull request closed without merging**
