### PR TITLE
overhauled-ChanakyaGPT

### PR DESCRIPTION
**Pull request by Nkovaturient**
Closes: #360 

- **Title** : Overhaul ChanakyaGPT
- **Name:** Neha Kumari
- **Idenitfy yourself:**  GSSOC Extd '24 || Contributor

### Describe the add-ons or changes you've made 📃

- Examined and overhaul chanakyaGPT:-
- replaced the groq-sdk with fast, resilient and reliable **Cohere-API**
- added proper logic and functionality
- responsiveness and styling suitable on various devices

### Type of change ☑️

What sort of change have you made:

- - [✅ ] Bug fix (non-breaking change which fixes an issue)
- - [ ✅ ] New feature (non-breaking change which adds functionality)
- - [✅  ] Code style update (formatting, local variables)

- ### Checklist: ☑️
- - [✅  ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.

- [✅  ] This PR does not contain plagiarized content.
- [✅  ] I have performed a self-review of my own code.
- [✅  ] I have commented my code, particularly wherever it was hard to understand.
- [✅  ] My changes generate no new warnings.

### Screenshots 📷

Screenshot (268)
Screenshot (267)

https://www.loom.com/share/1388d6914faa46178ace32c277b73379?sid=3841ba42-69f3-4e3b-87b4-5124c2c53823

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
Nice work. But UI not looks good. Maintain the website theme.

**Comment by Nkovaturient** [comment]
Hello @Avdhesh-Varshney , 
I hv made the desired changes. Here is the sc:-

Screenshot (269)

**Comment by Nkovaturient** [comment]
> Hello @Avdhesh-Varshney , I hv made the desired changes. Here is the sc:-
> 
> Screenshot (269)

Hey @Avdhesh-Varshney !
anything else u would like me to update?

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
It's still not responding.
image

**Comment by Nkovaturient** [comment]
> It's still not responding. image

Hello @Avdhesh-Varshney ,
it certainly has to do with the apiKey config/ import or deploy changes, bcuz GPT is workin perfectly fine in my codebase--
Demo of today-

https://www.loom.com/share/ece6321d8f0f4e858828a606987fa288?sid=f207aef7-3dba-4025-9002-740fed236f51

**Review by Avdhesh-Varshney — APPROVED** [review]
Ok, I'll fix it

**Comment by Nkovaturient** [comment]
> Ok, I'll fix it

Hey, i have fixed it

**Comment by Nkovaturient** [comment]
> Ok, I'll fix it

Basically it was package dependency issue
I have updated and resolved

**Pull request merged**
