### PR TITLE
visitors count and github stars added : #311 done

### PR DESCRIPTION
**Pull request by VinayLodhi1712**
Closes: #311 done

- **Title** : visitors count and github stars added : #311 done
- **Name:**: Vinay Anand Lodhi
- **Idenitfy yourself:** GSSoC Contributor

1. Added visitor count
2. Add scroll top with it
3. Added github star button with star showing.

### Type of change ☑️

What sort of change have you made:
- [ x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

- [x ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ x] This PR does not contain plagiarized content.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [ x] My changes generate no new warnings.

### Screenshots 📷

https://github.com/user-attachments/assets/6e6812fa-1c84-48e7-b65c-ee49a9f83afb

visitor3
visitor2

### Note to reviewers 📄
If you want to change style or you want to change it late you can go to the hitwebcounter website for help.

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
Create a simple icon for visitors count

**Comment by VinayLodhi1712** [comment]
@Avdhesh-Varshney sir i have changed something like that 
again

actually the count is generated by an website and that generate an image for that number and we have this type of options
hitcounter

and i thing current one is looking good see above image or you can choose one of that website options.

**Comment by Avdhesh-Varshney** [comment]
okay, but it is not visible?
image

**Comment by VinayLodhi1712** [comment]
it is visible at my device you should have wait for sometime i think if the issue persist than i will try again.

**Comment by VinayLodhi1712** [comment]
@Avdhesh-Varshney after merge conflict solved it looks like -
commit

**Comment by Avdhesh-Varshney** [comment]
It's not shown and I can't accept this cartoonify numbering for the website.

**Comment by VinayLodhi1712** [comment]
@Avdhesh-Varshney can you plz send a video if possible that it is not showing. on first time it is taking 10 sec at most then after it is showing . If it is not showing i would do once again by forking and make again changes and then i create a pull request and also i think this is the good looking visitors number.

visiting

**Comment by Avdhesh-Varshney** [comment]
image

After 1 minute, I've taked this ss

**Comment by VinayLodhi1712** [comment]
ok @Avdhesh-Varshney i think i have to again work on this issue so i am working again and then creating a new pr for it.

**Pull request closed without merging**
