### PR TITLE
Fast Load Chanakya image & make Home page and About page appealing in UI

### PR DESCRIPTION
**Pull request by shivamm-verma**
Closes: #187 

- **Title** : Fast Load Chanakya image & make Home page and About page appealing in UI
- **Name:** Shivam Verma
- **Identify yourself:** GSSOC

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made:
- Download Chanakya image from source, to faster Load up! (in assets folder)
- Added Smooth transition from Light Mode to Dark Mode
- Changed Bg colors of cards in Home Page and added better hover & shadow effects in Dark Mode.
- Changed Bg color of About Chanakya card to some % of beige

### Type of change ☑️
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️
- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Screenshots 📷
mentioned in the ISSUE itself.

### Note to reviewers 📄
Nil

### CODE REVIEW

**Comment by shivamm-verma** [comment]
Hey @Avdhesh-Varshney  Please check the deployment! (Authorization is required)

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
@shivamm-verma about section picture is not loaded

**Comment by shivamm-verma** [comment]
@Avdhesh-Varshney  Fixed

**Review by Avdhesh-Varshney — APPROVED** [review]
@shivamm-verma LGTM. PR Approved 🎉

**Pull request merged**
