### PR TITLE
add social icon in footer

### PR DESCRIPTION
**Pull request by ANKeshri**
Closes: #219

- **Title** : Add social icons with hover effect in footer of all pages .
- **Name:** **Aditya Narayan**
- **Idenitfy yourself:** **GSSOC** 

### Describe the add-ons or changes you've made 📃

Add social icons with hover effect in footer as shown in video .

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Chanakya-Niti/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Screenshots 📷

BEFORE : 

Screenshot 2024-07-11 230949

AFTER : 

https://github.com/Avdhesh-Varshney/chanakya-niti/assets/159682348/a5ca6fa6-0c28-4bc8-b28d-236d11ed69cb

### CODE REVIEW

**Comment by ANKeshri** [comment]
@Avdhesh-Varshney please review once and merge my pr and if possible please update level . 
Thank you , Excited to work more on this project .

**Comment by Avdhesh-Varshney** [comment]
enlist them in a list format

image

**Comment by ANKeshri** [comment]
@Avdhesh-Varshney done the required changes

**Comment by Avdhesh-Varshney** [comment]
No, I've told you to create a stack of contacts. Remove icons, just give the text as shown of resources section.

**Comment by ANKeshri** [comment]
> No, I've told you to create a stack of contacts. Remove icons, just give the text as shown of resources section.

ok sure i got it now

**Comment by ANKeshri** [comment]
Screenshot 2024-07-14 141222

**Comment by ANKeshri** [comment]
@Avdhesh-Varshney please review once and merge my pr

**Comment by Avdhesh-Varshney** [comment]
re-raise the pr. It can't be merged and replace facebook url with discord url and twitter url with youtube ok and add react-icons in front of the names.

**Pull request closed without merging**
